<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN3gexYZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN3gexYZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN3gexYZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN3gexYZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN3gexYZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'N3gexYZ',
    'container.build_id' => 'ec55327e',
    'container.build_time' => 1718356918,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN3gexYZ');
